import type { Metadata } from "next";
import { buildMetadata } from "@/lib/seo";
import type { ProductDetail } from "../pressure-vessels-and-storage/productDetails";

export const CATEGORY_NAME = "Custom Manufacturing (As per Client Drawing)";

export const customManufacturingNav = [
  {
    label: "Heavy Plate Fabrication",
    href: "/products/heavy-plate-fabrication",
  },
  {
    label: "SS / CS / Alloy Steel Fabrication",
    href: "/products/ss-cs-alloy-steel-fabrication",
  },
  {
    label: "On-site Erection Support",
    href: "/products/on-site-erection-support",
  },
  {
    label: "Repair / Modification Jobs",
    href: "/products/repair-modification-jobs",
  },
];

export const productDetails = {
  "heavy-plate-fabrication": {
    title: "Heavy Plate Fabrication in India",
    headline: "Heavy Plate Fabrication in Surat",
    description:
      "National Engineers & Steel Fabricators provides heavy plate fabrication in India for industrial projects that require custom plate cutting, forming, rolling, fit-up, welding, machining support, inspection and delivery of heavy-duty plate-built components and welded assemblies.",
    pagePath: "/products/heavy-plate-fabrication",
    image: "/product/16.jpg",
    imageAlt: "Heavy plate fabrication by National Engineers and Steel Fabricators",
    imagePosition: "center",
    quickFacts: [
      { label: "Product Type", value: "Heavy Plate Fabrication" },
      { label: "Scope", value: "Shells, casings, housings and welded assemblies" },
      { label: "Materials", value: "MS, CS, SS, alloy or structural steel" },
      { label: "Build Basis", value: "Client drawing and project specification" },
    ],
    overview: [
      "Based in Sachin GIDC, Surat, Gujarat, we manufacture heavy plate shells, casings, drums, housings, ducts, hoppers, bins, base sections, reinforcement plates, stiffened assemblies and custom plate-built equipment as per client drawings, material grades, plate thickness, forming requirements, welding requirements, dimensional tolerances, NDT scope, inspection plan, coating specification and delivery schedule.",
      "Our heavy plate fabrication solutions are suitable for industries that require strong, accurate and inspection-ready fabrication for demanding industrial service conditions.",
    ],
    sections: [
      {
        title: "Heavy Plate Fabrication in Surat",
        body: ["National Engineers & Steel Fabricators is an experienced heavy plate fabrication company in Surat, offering custom build-to-drawing fabrication for process equipment, industrial structures, plate-built housings, large welded assemblies, formed sections, rolled shells, casings, hoppers, bins, ducting sections and special-purpose fabricated components.", "As a heavy plate fabrication company in India, we work on client-supplied drawings, specifications, plate grades, dimensions, thicknesses, welding requirements, forming details, inspection requirements and documentation needs.", "Each fabricated plate assembly is manufactured with attention to cutting accuracy, fit-up quality, weld integrity, dimensional control, match-marking, surface preparation and dispatch readiness."],
      },
      {
        title: "Custom Heavy Plate Fabrication as per Client Drawing",
        body: ["Heavy plate fabrication is not a standard product supply. Every job depends on the drawing, plate thickness, material grade, geometry, load condition, weld joint details, tolerance requirement and inspection scope.", "National Engineers & Steel Fabricators provides custom heavy plate fabrication as per client drawings and project specifications. We can fabricate one-off components, repeat assemblies, replacement parts, retrofit sections and project-specific plate-built equipment.", "Our custom heavy plate fabrication scope can include:"],
        bullets: ["Heavy plate cutting", "Plate forming support", "Plate rolling support", "Plate bending support", "Plate fit-up and assembly", "Heavy plate welding", "Welded plate assemblies", "Rolled plate shells", "Formed plate sections", "Plate-built casings", "Fabricated housings", "Heavy plate drums", "Thick plate ducts", "Hopper and bin sections", "Reinforcement plates", "Stiffeners and gussets", "Base sections and heavy mounting plates", "Trial assembly where required", "Match-marking for site fitment", "Surface preparation and coating", "Inspection and documentation support"],
      },
      {
        title: "Heavy Plate Shells, Drums and Casings",
        body: ["National Engineers & Steel Fabricators manufactures heavy plate shells, drums and casings for industrial applications where strength, alignment, weld quality and dimensional accuracy are important.", "These plate-built components are commonly used in process equipment, ducting systems, pollution control equipment, bulk handling equipment, machine housings, heavy fabricated assemblies and custom manufacturing projects.", "Our fabrication can support:"],
        bullets: ["Rolled shells", "Plate-built drums", "Cylindrical casings", "Rectangular casings", "Large fabricated housings", "Stiffened casing sections", "Welded shell assemblies", "Plate-built equipment bodies", "Custom shells as per drawing"],
      },
      {
        title: "Plate-Built Housings and Large Welded Assemblies",
        body: ["Plate-built housings and large welded assemblies are used where standard rolled sections or standard fabricated parts cannot meet project requirements.", "National Engineers & Steel Fabricators manufactures plate-built housings and large welded assemblies as per project drawings, load requirement, material grade, welding scope and inspection plan.", "Our fabrication can include:"],
        bullets: ["Machine housings", "Industrial equipment housings", "Heavy-duty fabricated casings", "Stiffened plate housings", "Plate-built frames", "Welded enclosures", "Reinforced duct sections", "Special-purpose plate assemblies", "Custom equipment bodies", "Built-up fabricated components"],
      },
      {
        title: "Plate Cutting, Forming and Rolling Support",
        body: ["Heavy plate fabrication requires accurate cutting, forming and rolling before final assembly. The quality of these operations directly affects fit-up, weld gap, final dimensions and assembly integrity.", "National Engineers & Steel Fabricators supports heavy plate cutting, forming and rolling requirements as per client drawing and project specification.", "Fabrication can include:"],
        bullets: ["CNC plate cutting", "Plasma plate cutting", "Oxy plate cutting", "Straight plate cutting", "Profile cutting", "Edge preparation", "Plate rolling support", "Plate bending support", "Formed plate sections", "Shell segment preparation", "Curved plate sections", "Fit-up-ready plate parts"],
      },
      { title: "Heavy Plate Welding and Fit-Up", body: ["Welding is one of the most important stages in heavy plate fabrication. Proper fit-up, joint preparation, welding sequence and inspection help improve weld integrity and dimensional stability.", "National Engineers & Steel Fabricators performs welded fabrication based on client-approved drawings, welding requirements and inspection plans.", "Our welding and fit-up focus includes:"], bullets: ["Fit-up inspection", "Joint preparation", "Root gap control where applicable", "Tack welding control", "Welding sequence planning", "Distortion control support", "Weld visual inspection", "Dimensional control after welding", "NDT coordination where specified", "Repair and rework control as per project requirement"] },
      { title: "MS, CS, SS and Alloy Steel Plate Fabrication", body: ["National Engineers & Steel Fabricators undertakes heavy plate fabrication in different materials based on project requirement, service condition, corrosion risk, temperature, load and client specification.", "Common material options include:", "Material selection depends on service duty, design requirement, corrosion condition, temperature condition, inspection scope and documentation requirements."], bullets: ["Mild Steel plate fabrication", "Carbon Steel plate fabrication", "Stainless Steel plate fabrication", "Alloy Steel plate fabrication", "Boiler-quality plates where specified", "Structural steel plates", "Wear-resistant plates where specified", "Special MOC as per client requirement"] },
      { title: "Heavy Plate Fabrication for Industrial Equipment", body: ["Heavy plate fabrication is widely used in industrial equipment manufacturing where strong plate-built sections are required for process duty, structural support, containment, ducting, material handling or equipment protection.", "National Engineers & Steel Fabricators fabricates heavy plate components for:"], bullets: ["Process equipment bodies", "Shells and casings", "Ducting sections", "Scrubber bodies", "Hopper and bin sections", "Pressure-related fabricated components where specified", "Structural support assemblies", "Equipment base sections", "Machine housings", "Pollution control equipment", "Bulk handling equipment", "Custom plant equipment"] },
      { title: "Trial Assembly and Match-Marking", body: ["Large and heavy plate assemblies may need trial assembly, match-marking and modular dispatch to reduce site fit-up issues.", "National Engineers & Steel Fabricators can support trial assembly and match-marking for critical fabricated components where required by the project.", "Our site-fitment support can include:"], bullets: ["Trial fit-up of mating parts", "Match-marking", "Part identification", "Module-wise packing", "Connection interface checks", "Bolt-hole alignment checks", "Flange alignment checks", "Dispatch sequence planning", "Site installation-friendly marking"] },
      { title: "Types of Heavy Plate Fabrication We Undertake", body: ["National Engineers & Steel Fabricators undertakes custom heavy plate fabrication for different industrial applications.", "Common fabrication types include:"], bullets: ["Heavy plate fabrication", "Custom heavy plate fabrication", "Industrial heavy plate fabrication", "Steel plate fabrication", "Thick plate fabrication", "MS plate fabrication", "CS plate fabrication", "SS plate fabrication", "Alloy steel plate fabrication", "Heavy steel plate fabrication", "Plate-built shells", "Rolled plate shells", "Heavy plate drums", "Plate-built casings", "Fabricated housings", "Large welded assemblies", "Formed plate sections", "Plate-built ducts", "Plate-built hoppers", "Plate-built bins", "Reinforced plate assemblies", "Custom welded plate assemblies as per drawing"] },
      { title: "Key Features", bullets: ["Custom heavy plate fabrication as per client drawing", "Suitable for shells, casings, housings and welded assemblies", "Heavy plate cutting, rolling, forming and welding support", "MS, CS, SS and alloy steel plate fabrication options", "Thick plate fabrication for demanding industrial service", "Plate-built equipment bodies and custom assemblies", "Stiffeners, gussets and reinforcement work", "Fit-up and welding quality control", "Trial assembly and match-marking where required", "Dimensional inspection and weld inspection support", "NDT coordination where specified", "Surface preparation, painting and coating support", "Documentation support as per project requirement", "Dispatch planning for heavy and large fabricated assemblies"] },
      { title: "Applications", body: ["Our heavy plate fabrication solutions are used across different industrial applications, including:"], bullets: ["Process equipment manufacturing", "Heavy industrial fabrication", "Plate-built shells and casings", "Large fabricated housings", "Pollution control equipment", "Scrubber and ducting components", "Bulk material handling equipment", "Hopper and bin sections", "Equipment base sections", "Structural support assemblies", "Machine housings", "Utility plant fabrication", "Chemical plant fabrication", "Manufacturing plant projects", "Plant retrofit and replacement jobs", "Custom manufacturing as per client drawing"] },
      { title: "Materials of Construction", body: ["National Engineers & Steel Fabricators fabricates heavy plate assemblies using suitable materials based on service condition, design requirement, load, corrosion risk, temperature, fabrication process and client specification.", "Common material options include:", "Material selection is finalized based on client drawings, datasheets, service duty, inspection plan and project specification."], bullets: ["Mild Steel", "Carbon Steel", "Stainless Steel 304", "Stainless Steel 316", "Stainless Steel 316L", "Alloy Steel", "Boiler-quality plates where specified", "Structural steel plates", "Wear-resistant plates where specified", "Special plate grades as per client specification"] },
      { title: "Technical Specifications", table: { columns: ["Specification", "Details"], rows: [["Product Type", "Heavy Plate Fabrication"], ["Equipment Category", "Custom Manufacturing (As per Client Drawing)"], ["Application", "Plate-built shells, casings, housings, drums, ducts, hoppers, bins and welded assemblies"], ["Build Basis", "Client drawing, datasheet, specification, P&ID or project requirement"], ["Material of Construction", "MS, CS, SS, alloy steel, structural steel or as per requirement"], ["Plate Thickness", "As per client drawing and project requirement"], ["Plate Grade", "As per client specification"], ["Fabrication Scope", "Cutting, forming, rolling, fit-up, welding, assembly and finishing"], ["Cutting Method", "CNC, plasma, oxy, saw cutting or as per requirement"], ["Forming / Rolling", "Available as per geometry and thickness requirement"], ["Welding", "As per approved project requirement and inspection scope"], ["Assembly Type", "Shells, casings, housings, frames, sections or custom welded assemblies"], ["Reinforcement", "Stiffeners, gussets, ribs and support members as required"], ["Trial Assembly", "Available for critical assemblies where required"], ["Match-Marking", "Provided where site fitment or modular dispatch is required"], ["Surface Finish", "Primer, paint, epoxy, coating, blasting or as specified"], ["Inspection", "Dimensional inspection, weld visual inspection and NDT where specified"], ["Documentation", "Material traceability, inspection reports, NDT reports and QA/QC records as agreed"], ["Packing", "Heavy-duty packing and dispatch planning as per assembly size"], ["Customization", "Available as per drawing, plate grade, thickness, geometry, welding, inspection and delivery requirement"]] } },
      { title: "Fabrication and Quality Control", body: ["Every heavy plate fabrication job is executed with proper attention to material verification, drawing review, cutting accuracy, fit-up, welding quality, dimensional control, distortion control, reinforcement placement, surface preparation and final inspection.", "Quality checks may include:"], bullets: ["Material verification", "Drawing and specification review", "Plate grade and thickness verification", "Cutting inspection", "Edge preparation check", "Rolling and forming checks where applicable", "Fit-up inspection", "Weld joint inspection", "Welding quality checks", "Dimensional inspection", "Diagonal and alignment checks", "Shell roundness checks where applicable", "Flange and interface checks where applicable", "Stiffener and gusset checks", "Trial assembly where required", "NDT where specified", "Surface preparation checks", "Painting or coating checks", "Marking and packing checks", "Documentation compilation as agreed"] },
      { title: "Inspection, NDT and Documentation", body: ["Heavy plate fabrication often requires documented quality records because fabricated assemblies are used in demanding industrial environments.", "National Engineers & Steel Fabricators can support project-specific inspection and documentation requirements.", "Documentation support may include:"], bullets: ["Material records", "Traceability records", "Dimensional inspection reports", "Weld inspection reports", "NDT reports where applicable", "ITP and hold-point support where agreed", "Surface preparation records", "Coating records", "Final inspection records", "Dispatch documents", "QA/QC documentation pack as agreed"] },
      { title: "Why Choose National Engineers?", body: ["National Engineers & Steel Fabricators is a trusted heavy plate fabrication company in Surat, Gujarat, providing build-to-drawing plate fabrication for industrial projects that require strength, alignment, weld integrity and documented quality.", "Reasons to work with us:"], bullets: ["Experienced heavy plate fabrication company in India", "Reliable heavy plate fabrication in Surat, Gujarat", "Custom plate fabrication as per client drawing", "Heavy plate cutting, forming, rolling and welding support", "Plate-built shells, casings, housings and welded assemblies", "MS, CS, SS and alloy steel plate fabrication capability", "Stiffeners, gussets and reinforcement fabrication", "Trial assembly and match-marking where required", "Dimensional inspection and weld inspection support", "NDT and ITP support where specified", "Surface preparation, painting and coating support", "Fabrication for process equipment, pollution control, bulk handling and custom manufacturing projects"] },
      { title: "Details Required for Quotation", body: ["To provide the right quotation for heavy plate fabrication, please share:"], bullets: ["Fabrication drawing", "GA drawing", "Datasheet if available", "Plate grade", "Plate thickness", "Approximate weight or quantity", "Cutting requirement", "Rolling requirement", "Forming or bending requirement", "Welding requirement", "Machining requirement if any", "Tolerance and dimensional requirement", "NDT requirement", "ITP or inspection plan requirement", "Surface preparation requirement", "Painting or coating requirement", "Trial assembly requirement", "Match-marking requirement", "Module size or transport constraints", "Delivery location and timeline"] },
      { title: "Get a Quote for Heavy Plate Fabrication", body: ["Looking for heavy plate fabrication in India?", "Share your drawings, plate grades, thicknesses, forming requirements, welding details, dimensional tolerances, NDT scope, inspection plan, coating requirement and delivery schedule with National Engineers & Steel Fabricators. Our team will review your requirement and provide a suitable fabrication scope and quotation basis for your custom manufacturing project."] },
    ],
    note:
      "Share your drawings, plate grades, thicknesses, forming requirements, welding details, dimensional tolerances, NDT scope, inspection plan and coating requirement.",
    enquiry: {
      title: "Request a quote for Heavy Plate Fabrication",
      subtitle: "Share your drawings, plate grades, forming, welding, inspection, and delivery requirements.",
      productName: "Heavy Plate Fabrication",
      buttonText: "Request Quote",
    },
    faqs: [
      { question: "What is heavy plate fabrication?", answer: "Heavy plate fabrication is the process of cutting, forming, rolling, welding and assembling thick steel plates into shells, casings, housings, drums, ducts, hoppers, bins and custom industrial assemblies." },
      { question: "Who provides heavy plate fabrication in Surat?", answer: "National Engineers & Steel Fabricators provides heavy plate fabrication in Surat, Gujarat, for plate-built shells, casings, housings, large welded assemblies, industrial equipment components and custom manufacturing projects." },
      { question: "Does NESF provide heavy plate fabrication in India?", answer: "Yes, National Engineers & Steel Fabricators provides heavy plate fabrication in India as per client drawings, plate grades, thicknesses, forming requirements, welding details, NDT scope and inspection requirements." },
      { question: "Can heavy plate fabrication be done as per client drawing?", answer: "Yes, heavy plate fabrication can be done as per client drawings, datasheets, plate grades, dimensions, tolerances, welding requirements, NDT requirements, coating specification and delivery constraints." },
      { question: "What components can be made through heavy plate fabrication?", answer: "Heavy plate fabrication can be used to manufacture rolled shells, drums, casings, large housings, plate-built ducts, hoppers, bins, reinforcement plates, base sections, stiffened assemblies and custom welded structures." },
      { question: "What materials are used for heavy plate fabrication?", answer: "Heavy plate fabrication can be done using mild steel, carbon steel, stainless steel, alloy steel, structural steel, boiler-quality plates or special plate grades as per client specification." },
      { question: "What is the difference between heavy plate fabrication and heavy structural fabrication?", answer: "Heavy plate fabrication focuses on thick plate cutting, rolling, forming and welded plate assemblies. Heavy structural fabrication focuses more on frames, racks, platforms, beams, columns and structural modules." },
      { question: "What quality checks are done during heavy plate fabrication?", answer: "Quality checks may include material verification, cutting inspection, fit-up inspection, weld visual inspection, dimensional inspection, shell roundness checks, flange alignment checks, NDT where specified and final inspection." },
      { question: "What details are required to get a quotation?", answer: "To get a quotation, you can share fabrication drawings, plate grade, plate thickness, quantity, forming or rolling requirement, welding details, tolerance requirement, NDT scope, coating and delivery schedule." },
      { question: "How is heavy plate fabrication price calculated?", answer: "Heavy plate fabrication price depends on plate grade, thickness, weight, cutting complexity, forming or rolling scope, welding quantity, machining, tolerance, NDT, coating, trial assembly, packing and delivery requirements." },
    ],
    seo: {
      title: "Heavy Plate Fabrication in India | NESF",
      description:
        "Heavy plate fabrication in Surat, India, offering custom plate cutting, rolling, forming, welding, shells, casings and assemblies.",
      keywords: [
        "heavy plate fabrication", "heavy plate fabrication in India", "heavy plate fabrication in Surat", "heavy plate fabrication company", "heavy plate fabrication company in India", "heavy plate fabrication company in Surat", "custom heavy plate fabrication", "industrial heavy plate fabrication", "plate fabrication", "plate fabrication company", "steel plate fabrication", "thick plate fabrication", "MS plate fabrication", "CS plate fabrication", "SS plate fabrication", "alloy steel plate fabrication", "heavy steel plate fabrication", "custom plate-built assemblies", "welded plate assemblies", "plate-built shells", "plate-built casings", "fabricated housings", "heavy plate shells", "rolled plate shells", "formed plate sections", "plate rolling fabrication", "plate bending fabrication", "plate cutting and welding", "CNC plate cutting", "plasma plate cutting", "oxy plate cutting", "heavy welded assemblies", "trial assembly", "match marking", "NDT", "dimensional inspection", "weld inspection", "ITP", "QA/QC documentation",
      ],
    },
  },
  "ss-cs-alloy-steel-fabrication": {
    title: "SS CS Alloy Steel Fabrication in India",
    headline: "SS CS Alloy Steel Fabrication in Surat",
    description:
      "National Engineers & Steel Fabricators provides SS CS alloy steel fabrication in India for industries that require custom-built equipment, welded assemblies, plate-built components, structural parts, process equipment, ducting sections, support frames and heavy fabrication as per client drawings and project specifications.",
    pagePath: "/products/ss-cs-alloy-steel-fabrication",
    image: "/product/24.jpeg",
    imageAlt: "Stainless steel carbon steel and alloy steel fabrication by National Engineers",
    imagePosition: "center",
    quickFacts: [
      { label: "Service Type", value: "SS / CS / Alloy Steel Fabrication" },
      { label: "Materials", value: "SS, CS, MS, pressure-grade or alloy steel" },
      { label: "Build Basis", value: "Drawings, datasheets and MOC schedule" },
      { label: "Inspection", value: "Dimensional, weld and NDT as specified" },
    ],
    overview: [
      "Based in Sachin GIDC, Surat, Gujarat, we undertake stainless steel fabrication, carbon steel fabrication and alloy steel fabrication as per drawings, datasheets, material of construction, service conditions, welding requirements, NDT requirements, inspection plan, surface finish, documentation scope and delivery schedule.",
      "Our SS, CS and alloy steel fabrication solutions are suitable for process plants, chemical industries, utilities, oil and gas projects, fertilizer plants, petrochemical units, ETP systems, heavy industry and custom manufacturing projects where material compatibility, weld quality, fit-up accuracy and traceability are important.",
    ],
    sections: [
      {
        title: "SS CS Alloy Steel Fabrication in Surat",
        body: ["National Engineers & Steel Fabricators is an experienced SS CS alloy steel fabrication company in Surat, offering build-to-drawing fabrication in stainless steel, carbon steel, pressure-grade steel, structural steel and alloy steel for industrial applications.", "As a custom steel fabrication company in India, we fabricate welded assemblies, process equipment parts, heavy plate components, support structures, ducting sections, skids, frames, platforms, liners, shells, casings and special-purpose fabricated components as per client requirements.", "Each fabrication job is executed with attention to material identification, weld quality, dimensional accuracy, fit-up precision, inspection requirements, NDT scope, surface finish and documentation support."],
      },
      {
        title: "Stainless Steel Fabrication",
        body: ["National Engineers & Steel Fabricators provides stainless steel fabrication for industries where corrosion resistance, clean finish, chemical compatibility, hygiene or process-area suitability is required.", "Stainless steel fabrication is commonly used in chemical plants, pharmaceutical facilities, food processing areas, water treatment systems, scrubber systems, process equipment, ducting, tanks, internals and custom fabricated assemblies.", "Our stainless steel fabrication scope can include:", "Material grade is selected as per client specification, corrosion condition, service media, temperature and inspection requirement."],
        bullets: ["SS 304 fabrication", "SS 304L fabrication", "SS 316 fabrication", "SS 316L fabrication", "Stainless steel welded assemblies", "Stainless steel process equipment parts", "Stainless steel ducting sections", "Stainless steel hoppers and bins", "Stainless steel liners and internals", "Stainless steel support frames", "Stainless steel custom components as per drawing"],
      },
      {
        title: "Carbon Steel Fabrication",
        body: ["National Engineers & Steel Fabricators provides carbon steel fabrication for industrial equipment, structures, pressure-related components, utility systems, process assemblies and heavy fabricated items.", "Carbon steel is widely used in industrial fabrication because it offers strength, weldability and suitability for many process and structural applications.", "Our carbon steel fabrication scope can include:", "Carbon steel fabrication can be carried out using project-specified grades, thicknesses, welding procedures, NDT scope and documentation requirements."],
        bullets: ["CS welded assemblies", "CS plate-built components", "CS shells and casings", "CS ducting sections", "CS support frames", "CS process equipment components", "CS structural assemblies", "CS base frames and skids", "CS hoppers, bins and chutes", "CS custom fabrication as per drawing"],
      },
      {
        title: "Alloy Steel Fabrication",
        body: ["Alloy steel fabrication is used where the service condition requires improved strength, temperature resistance, wear resistance or special mechanical properties compared to general carbon steel.", "National Engineers & Steel Fabricators undertakes alloy steel fabrication as per client drawings, material specifications, welding requirements and inspection scope.", "Alloy steel fabrication may be used for:", "Alloy steel fabrication requires proper material identification, welding control, traceability and inspection discipline."],
        bullets: ["High-temperature service components", "Heavy-duty process equipment parts", "Wear-related components", "Special-purpose welded assemblies", "Pressure-grade applications where specified", "Custom plant equipment", "Industrial replacement components", "Heavy fabricated assemblies"],
      },
      {
        title: "Pressure-Grade and Structural Steel Fabrication",
        body: ["National Engineers & Steel Fabricators can fabricate using pressure-grade and structural steel materials where specified by project drawings and datasheets.", "Common examples include pressure-grade carbon steels such as SA 516 Gr.70 and structural carbon steels such as IS 2062, along with other client-specified grades.", "Our pressure-grade and structural steel fabrication can support:", "Final material grade, welding method, inspection scope and documentation are followed as per client requirement."],
        bullets: ["Process equipment parts", "Shell sections", "Tank and vessel components", "Support structures", "Base frames", "Heavy equipment frames", "Industrial skids", "Structural assemblies", "Plate-built items", "Custom components as per drawing"],
      },
      { title: "Multi-Material Fabrication", body: ["Many industrial projects require multi-material fabrication where stainless steel, carbon steel and alloy steel components are combined within one assembly or project scope.", "National Engineers & Steel Fabricators supports multi-material fabrication with proper material identification, segregation, traceability and fabrication control as required by the project.", "Multi-material fabrication may include:"], bullets: ["SS and CS combination assemblies", "CS structures with SS contact parts", "SS liners with CS backing structure", "Alloy steel components with CS frames", "Multi-MOC process equipment", "Multi-material ducting sections", "Custom assemblies with different material zones", "Fabrication as per MOC schedule and drawing notes"] },
      { title: "Custom Steel Fabrication as per Drawing", body: ["Every SS, CS and alloy steel fabrication project has different geometry, MOC, weld joint details, service conditions, tolerances and inspection requirements. That is why National Engineers & Steel Fabricators provides custom fabrication as per client drawing instead of standard product supply.", "Our custom steel fabrication scope can include:"], bullets: ["Build-to-drawing fabrication", "Stainless steel fabrication", "Carbon steel fabrication", "Alloy steel fabrication", "Pressure-grade steel fabrication", "Plate cutting and forming", "Fit-up and welding", "Welded assembly fabrication", "Shell and casing fabrication", "Ducting section fabrication", "Hopper and bin fabrication", "Base frame and skid fabrication", "Platform and structural component fabrication", "Process equipment component fabrication", "Trial assembly where required", "Match-marking where required", "Surface preparation and coating", "Inspection and documentation support"] },
      { title: "Custom Welded Assemblies", body: ["National Engineers & Steel Fabricators manufactures custom welded assemblies in SS, CS and alloy steel for industrial equipment and plant fabrication projects.", "Custom welded assemblies may include:", "Welded assemblies are fabricated with proper fit-up, weld sequence planning, weld visual checks and inspection support as agreed."], bullets: ["Process equipment assemblies", "Support assemblies", "Fabricated housings", "Heavy plate assemblies", "Ducting assemblies", "Piping-related assemblies", "Structural assemblies", "Skid-mounted assemblies", "Multi-component welded structures", "Replacement assemblies", "Retrofit fabrication components", "Custom industrial parts as per drawing"] },
      { title: "Material Traceability and Identification", body: ["Material traceability is important in SS, CS and alloy steel fabrication because the final equipment or assembly must match the specified MOC and project requirements.", "National Engineers & Steel Fabricators follows project-specific material identification and traceability practices as agreed with the client.", "Traceability support may include:"], bullets: ["Material grade verification", "Heat number identification where applicable", "MTC review where required", "Material segregation for different MOC", "Marking and identification during fabrication", "Traceability records as agreed", "Documentation support for project QA/QC"] },
      { title: "Welding, NDT and Inspection Support", body: ["SS, CS and alloy steel fabrication requires disciplined welding and inspection control. Welding requirements may vary depending on material grade, thickness, service condition and project specification.", "National Engineers & Steel Fabricators supports welding and inspection requirements as per client-approved scope.", "Inspection and quality support may include:"], bullets: ["Qualified welding as per project requirement", "Fit-up inspection", "Weld visual inspection", "Dimensional inspection", "NDT support where specified", "Inspection and test plan support where agreed", "Hold-point support where required", "Surface finish checks", "Coating inspection where applicable", "Final inspection documentation"] },
      { title: "Types of SS, CS and Alloy Steel Fabrication We Undertake", body: ["National Engineers & Steel Fabricators undertakes custom material-based fabrication for different industrial requirements.", "Common fabrication types include:"], bullets: ["SS CS alloy steel fabrication", "Stainless steel fabrication", "Carbon steel fabrication", "Alloy steel fabrication", "Pressure-grade steel fabrication", "Structural steel fabrication", "Custom steel fabrication", "Industrial steel fabrication", "Custom metal fabrication", "Build-to-drawing fabrication", "Custom welded assemblies", "Stainless steel welded assemblies", "Carbon steel welded assemblies", "Alloy steel welded assemblies", "Plate-built assemblies", "Process equipment fabrication", "Heavy fabricated sections", "Ducting and casing fabrication", "Skid and frame fabrication", "Support structure fabrication", "Multi-material assemblies as per drawing"] },
      { title: "Key Features", bullets: ["SS, CS and alloy steel fabrication as per client drawing", "Stainless steel, carbon steel and alloy steel fabrication capability", "Build-to-drawing fabrication for industrial projects", "Custom welded assemblies and plate-built components", "Pressure-grade and structural steel fabrication support", "Multi-material fabrication as per MOC schedule", "Controlled fit-up and welding quality", "Material identification and traceability support", "Dimensional inspection and weld visual inspection", "NDT support where specified by project requirement", "ITP and QA/QC documentation support where agreed", "Surface preparation, painting, coating or finishing as specified", "Trial assembly and match-marking where required", "Fabrication for process plants, utilities and heavy industry"] },
      { title: "Applications", body: ["Our SS, CS and alloy steel fabrication services are used across different industrial applications, including:"], bullets: ["Process equipment fabrication", "Chemical plant fabrication", "Petrochemical plant fabrication", "Oil and gas fabrication", "Fertilizer plant fabrication", "Utility system fabrication", "Effluent treatment plant fabrication", "Water treatment system fabrication", "Pollution control equipment fabrication", "Scrubber and ducting fabrication", "Bulk material handling fabrication", "Heavy equipment frame fabrication", "Skid and base frame fabrication", "Custom plant equipment fabrication", "Structural component fabrication", "Replacement and retrofit components", "Build-to-drawing custom manufacturing projects"] },
      { title: "Industries Served", body: ["National Engineers & Steel Fabricators provides SS, CS and alloy steel fabrication for industries that require project-specific fabrication, inspection and documentation.", "Industries served include:"], bullets: ["Chemical industries", "Petrochemical industries", "Oil and gas projects", "Fertilizer plants", "Utilities", "Effluent treatment plants", "Water treatment plants", "Steel plants", "Shipbuilding support applications", "Heavy engineering industries", "Process industries", "Manufacturing plants", "Bulk handling plants", "Pollution control system manufacturers", "Industrial equipment manufacturers"] },
      { title: "Materials of Construction", body: ["National Engineers & Steel Fabricators works with stainless steel, carbon steel, pressure-grade steel, alloy steel and structural steel grades as per client drawings and project specifications.", "Common material categories include:", "Final MOC is selected by the client or project design team based on service media, corrosion condition, temperature, load, pressure requirement and inspection scope."], bullets: ["Stainless Steel 304", "Stainless Steel 304L", "Stainless Steel 316", "Stainless Steel 316L", "Carbon Steel", "Mild Steel", "Structural Steel", "IS 2062", "SA 516 Gr.70", "Alloy Steel", "Pressure-grade steels", "Special MOC as per client specification"] },
      { title: "Technical Specifications", table: { columns: ["Specification", "Details"], rows: [["Service Type", "SS / CS / Alloy Steel Fabrication"], ["Equipment Category", "Custom Manufacturing (As per Client Drawing)"], ["Application", "Custom equipment, welded assemblies, structures, shells, casings, ducts, frames and plant components"], ["Build Basis", "Client drawings, datasheets, MOC schedule, P&ID or project specification"], ["Material of Construction", "SS, CS, MS, pressure-grade steel, alloy steel or as per requirement"], ["Common SS Grades", "SS 304, SS 304L, SS 316, SS 316L or as specified"], ["Common CS / Structural Grades", "Carbon steel, IS 2062, SA 516 Gr.70 or as specified"], ["Fabrication Scope", "Cutting, forming, fit-up, welding, assembly, finishing and documentation"], ["Assembly Type", "Welded assemblies, plate-built components, structures, frames, shells, casings or custom parts"], ["Welding", "As per project welding requirement"], ["Material Traceability", "Available as per project QA/QC requirement"], ["Inspection", "Dimensional inspection, weld visual inspection and client-specified checks"], ["NDT", "RT, UT, MPT, DPT or other methods where specified"], ["ITP Support", "Available where agreed with client and project requirement"], ["Surface Finish", "Painting, coating, passivation, polishing, blasting or as specified"], ["Documentation", "MTC, traceability, inspection reports, NDT reports and QA/QC records as agreed"], ["Trial Assembly", "Available for critical assemblies where required"], ["Packing", "Packed and marked as per delivery and installation requirement"], ["Customization", "Available as per drawing, MOC, welding, NDT, documentation and delivery schedule"]] } },
      { title: "Fabrication and Quality Control", body: ["Every SS, CS and alloy steel fabrication job is executed with proper attention to material verification, MOC identification, cutting accuracy, forming, fit-up, welding quality, dimensional control, inspection requirement and final documentation.", "Quality checks may include:"], bullets: ["Drawing and specification review", "Material verification", "MOC identification", "Heat number tracking where required", "Cutting inspection", "Fit-up inspection", "Welding quality checks", "Weld visual inspection", "Dimensional inspection", "Interface alignment checks", "Trial assembly where required", "NDT where specified", "Surface preparation checks", "Painting, coating or passivation checks where applicable", "Part marking and identification", "Packing and dispatch readiness checks", "Documentation compilation as agreed"] },
      { title: "Inspection, ITP and Documentation", body: ["Custom fabrication jobs often require documented quality records for client approval, third-party inspection, project handover or long-term plant maintenance records.", "National Engineers & Steel Fabricators can support documentation as per agreed project scope.", "Documentation may include:"], bullets: ["Material Test Certificates", "Material traceability records", "Fit-up inspection records", "Weld inspection records", "Dimensional inspection reports", "NDT reports where applicable", "ITP records where agreed", "Surface preparation records", "Coating or finish records", "Final inspection reports", "Dispatch documents", "QA/QC documentation pack as agreed"] },
      { title: "Why Choose National Engineers?", body: ["National Engineers & Steel Fabricators is a trusted SS CS alloy steel fabrication company and custom steel fabrication company in Surat, Gujarat. We provide build-to-drawing fabrication for industrial projects that require material compatibility, weld integrity, dimensional accuracy and documented quality.", "Reasons to work with us:"], bullets: ["Experienced SS CS alloy steel fabrication company in India", "Reliable custom fabrication company in Surat, Gujarat", "Stainless steel, carbon steel and alloy steel fabrication capability", "Build-to-drawing fabrication as per client requirement", "Custom welded assemblies and process equipment components", "Pressure-grade and structural steel fabrication support", "Multi-material fabrication as per MOC schedule", "Material traceability and identification support", "Controlled fit-up and qualified welding support", "NDT, ITP and QA/QC documentation support where specified", "Surface preparation, coating, painting or finishing support", "Fabrication for chemical, petrochemical, utilities, ETP, oil and gas and heavy industry"] },
      { title: "Details Required for Quotation", body: ["To provide the right quotation for SS, CS and alloy steel fabrication, please share:"], bullets: ["Fabrication drawings", "GA drawings", "Datasheets", "P&ID if applicable", "Material of construction", "Steel grade", "Plate thickness or section sizes", "Quantity required", "Service conditions", "Corrosion requirements", "Welding requirements", "NDT requirements", "ITP or inspection plan", "Dimensional tolerance requirements", "Surface finish requirement", "Painting, coating, passivation or polishing requirement", "Documentation requirements", "Packing requirements", "Delivery location and timeline"] },
      { title: "Get a Quote for SS CS Alloy Steel Fabrication", body: ["Looking for SS CS alloy steel fabrication in India?", "Share your drawings, datasheets, MOC, steel grade, quantities, welding requirements, NDT scope, inspection plan, surface finish and documentation requirements with National Engineers & Steel Fabricators. Our team will review your requirement and provide a suitable fabrication scope and quotation basis for your custom manufacturing project."] },
    ],
    note:
      "Share your drawings, datasheets, MOC, steel grade, quantities, welding requirements, NDT scope, inspection plan, surface finish and documentation requirements.",
    enquiry: {
      title: "Request a quote for SS / CS / Alloy Steel Fabrication",
      subtitle: "Share your drawings, MOC, quantities, welding, inspection, and schedule requirements.",
      productName: "SS / CS / Alloy Steel Fabrication",
      buttonText: "Request Quote",
    },
    faqs: [
      { question: "What is SS CS alloy steel fabrication?", answer: "SS CS alloy steel fabrication means manufacturing custom industrial equipment, welded assemblies, structures, shells, casings, frames and components using stainless steel, carbon steel and alloy steel as per client drawings." },
      { question: "Who provides SS CS alloy steel fabrication in Surat?", answer: "National Engineers & Steel Fabricators provides SS CS alloy steel fabrication in Surat, Gujarat, for process plants, utilities, heavy industry, oil and gas, petrochemical, fertilizer and custom manufacturing projects." },
      { question: "Does NESF provide stainless steel fabrication in India?", answer: "Yes, National Engineers & Steel Fabricators provides stainless steel fabrication in India for process equipment, ducting, tanks, internals, hoppers, supports, welded assemblies and custom components as per drawing." },
      { question: "Does NESF provide carbon steel fabrication?", answer: "Yes, NESF provides carbon steel fabrication for industrial equipment, support structures, welded assemblies, heavy plate components, ducting, skids, frames and process equipment parts." },
      { question: "Can alloy steel fabrication be done as per client drawing?", answer: "Yes, alloy steel fabrication can be done as per client drawings, steel grade, welding requirements, service conditions, NDT scope, inspection plan and documentation requirements." },
      { question: "What materials are used in SS CS alloy steel fabrication?", answer: "Materials may include SS 304, SS 304L, SS 316, SS 316L, carbon steel, mild steel, IS 2062, SA 516 Gr.70, alloy steel and other client-specified grades." },
      { question: "What is multi-material fabrication?", answer: "Multi-material fabrication means fabricating assemblies that use more than one material of construction, such as stainless steel and carbon steel combinations or alloy steel components with carbon steel frames." },
      { question: "What quality checks are done during steel fabrication?", answer: "Quality checks may include material verification, MOC identification, fit-up inspection, weld visual inspection, dimensional inspection, NDT where specified, surface finish checks and documentation review." },
      { question: "What details are required to get a quotation?", answer: "To get a quotation, you can share drawings, datasheets, MOC, steel grade, quantities, service conditions, welding requirement, NDT scope, inspection plan, surface finish and documentation requirements." },
      { question: "How is SS CS alloy steel fabrication price calculated?", answer: "Price depends on material grade, plate thickness, section size, weight, fabrication complexity, welding scope, forming requirement, machining, NDT, surface finish, documentation, packing and delivery schedule." },
    ],
    seo: {
      title: "SS, CS & Alloy Steel Fabrication in India | NESF",
      description:
        "SS, CS and alloy steel fabrication in Surat, India, offering custom welded assemblies, shells, structures, NDT and documentation.",
      keywords: [
        "SS CS alloy steel fabrication", "SS CS alloy steel fabrication in India", "SS CS alloy steel fabrication in Surat", "stainless steel fabrication", "stainless steel fabrication in India", "stainless steel fabrication in Surat", "carbon steel fabrication", "carbon steel fabrication in India", "carbon steel fabrication in Surat", "alloy steel fabrication", "alloy steel fabrication in India", "alloy steel fabrication in Surat", "SS fabrication company", "CS fabrication company", "alloy steel fabrication company", "custom steel fabrication", "custom steel fabrication in India", "custom metal fabrication", "industrial steel fabrication", "build to drawing fabrication", "as per drawing fabrication", "custom welded assemblies", "stainless steel welded assemblies", "carbon steel welded assemblies", "alloy steel welded assemblies", "pressure grade steel fabrication", "SA 516 Gr 70 fabrication", "IS 2062 fabrication", "SS 304L fabrication", "SS 316L fabrication", "multi material fabrication", "process equipment fabrication", "heavy fabrication company in Surat", "material traceability", "qualified welding", "NDT", "ITP", "dimensional inspection", "QA/QC documentation",
      ],
    },
  },
  "on-site-erection-support": {
    title: "On-Site Erection Support in India",
    headline: "On-Site Erection Support in Surat",
    description:
      "National Engineers & Steel Fabricators provides on-site erection support in India for clients who require installation assistance, positioning support, alignment support, fit-up coordination and site integration support for fabricated equipment, heavy fabricated assemblies, structural components, ducting systems, skids, support frames, tanks, vessels and custom-manufactured items.",
    pagePath: "/products/on-site-erection-support",
    image: "/gallery/Work in progress (46).JPG",
    imageAlt: "Industrial fabrication and erection support by National Engineers",
    imagePosition: "center",
    quickFacts: [
      { label: "Service Type", value: "On-Site Erection Support" },
      { label: "Support", value: "Positioning, alignment, fit-up and interfaces" },
      { label: "Planning", value: "Lifting coordination and erection sequencing" },
      { label: "Build Basis", value: "Installation scope and site conditions" },
    ],
    overview: [
      "Based in Sachin GIDC, Surat, Gujarat, we support clients from fabrication planning to site installation by helping with erection sequence, interface checks, site measurement validation, match-marking, lifting coordination, alignment verification, final fit-up and commissioning-readiness assistance as per agreed project scope.",
      "Our on-site erection support is suitable for projects where fabricated items must be installed safely, correctly and efficiently within site constraints, access limitations, crane capacity, shutdown window and existing plant conditions.",
    ],
    sections: [
      {
        title: "On-Site Erection Support in Surat",
        body: ["National Engineers & Steel Fabricators provides on-site erection support in Surat and across project locations in India for fabricated equipment and industrial assemblies manufactured as per client drawings.", "Our site support can help clients during installation of pressure vessels, storage tanks, ducting systems, scrubbers, hoppers, bins, skids, pipe supports, heavy structural assemblies, custom plate-built equipment and special fabricated components.", "As an experienced industrial fabrication company in Surat, we understand that fabrication quality is only complete when the item fits correctly at site. Our erection support focuses on reducing interface mismatch, alignment delay, fit-up rework and installation coordination issues."],
      },
      {
        title: "Industrial Erection Support Services",
        body: ["Industrial erection support is required when fabricated equipment or structural assemblies need to be safely positioned, aligned and integrated with plant systems.", "National Engineers & Steel Fabricators provides erection support services as per project scope, site condition and client requirements.", "Our support can include:"],
        bullets: ["Positioning support", "Alignment support", "Fit-up support", "Site measurement validation", "Interface checking", "Lifting coordination assistance", "Erection sequence planning support", "Match-marking coordination", "Bolt-hole and flange alignment checks", "Site constraint review", "Installation-readiness checks", "Punch-list closure support", "Commissioning-readiness assistance where included in scope"],
      },
      {
        title: "Fabricated Equipment Installation Support",
        body: ["Fabricated equipment installation requires coordination between fabrication drawings, actual site conditions, foundation details, existing plant interfaces, lifting resources and installation sequence.", "National Engineers & Steel Fabricators provides fabricated equipment installation support for custom-built items such as:", "Our installation assistance helps clients ensure that fabricated items are positioned and aligned as per drawing and site requirement."],
        bullets: ["Pressure vessels", "Storage tanks", "Process equipment", "Skid-mounted packages", "Ducting systems", "Scrubbers", "Hoppers and bins", "Heavy plate assemblies", "Structural frames", "Base frames", "Equipment support frames", "Pipe supports and saddle assemblies", "Custom fabricated components"],
      },
      {
        title: "Positioning, Alignment and Fit-Up Support",
        body: ["Correct positioning, alignment and fit-up are critical during site erection. Even small errors in foundation level, interface location, nozzle orientation, duct flange position or anchor alignment can create rework.", "National Engineers & Steel Fabricators supports positioning and alignment activities as per agreed scope.", "This may include:"],
        bullets: ["Checking equipment orientation", "Verifying base and anchor interface", "Supporting level and alignment activities", "Checking flange matching", "Validating duct or pipe interface points", "Supporting fit-up before final tightening or welding", "Helping identify mismatch before final installation", "Coordinating with client site teams and contractors"],
      },
      { title: "Site Measurement Validation and Interface Checks", body: ["Existing plant conditions may differ from drawings due to site modifications, civil tolerances, previous installations or access constraints. Site measurement validation helps reduce surprises during erection.", "National Engineers & Steel Fabricators can support site measurement validation and interface checks before final installation.", "Interface checks may include:"], bullets: ["Foundation interface check", "Anchor bolt location review", "Equipment orientation check", "Nozzle and flange interface check", "Duct connection interface check", "Pipe connection interface check", "Support location check", "Access and maintenance clearance check", "Crane and lifting access review", "Existing plant obstruction review"] },
      { title: "Lifting and Erection Sequencing Support", body: ["Heavy fabricated items require practical lifting and erection sequencing. The lifting method, crane access, work area, handling path and module size can directly affect project execution.", "National Engineers & Steel Fabricators can assist with erection sequence planning and lifting coordination as per agreed scope.", "Support may include:", "Final lifting plans, safety approvals and crane operations remain subject to client, site contractor and competent safety authority requirements."], bullets: ["Reviewing lifting constraints", "Coordinating erection sequence", "Planning module-wise installation support", "Checking lifting lug and handling point requirements", "Supporting safe handling coordination", "Reviewing crane access limitations", "Planning installation around site access", "Supporting client and contractor coordination", "Assisting during critical equipment positioning"] },
      { title: "Shutdown and Turnaround Erection Support", body: ["Shutdown jobs often have limited time, strict safety requirements and high pressure to complete installation without rework. Fabricated components must be ready, marked, packed and aligned with the shutdown sequence.", "National Engineers & Steel Fabricators provides support for shutdown erection activities where installation assistance, fit-up validation and punch-list closure are required.", "Shutdown support may include:"], bullets: ["Pre-shutdown site checks", "Shutdown installation planning support", "Match-marking review", "Replacement component fit-up support", "Alignment assistance", "Interface validation", "Punch-list closure support", "Final readiness checks", "Coordination with client maintenance teams", "Coordination with site contractors as agreed"] },
      { title: "Match-Marking and Site-Friendly Fabrication Support", body: ["Site erection becomes easier when fabricated parts are planned, marked and packed as per installation sequence. Match-marking helps site teams identify correct parts and reduce fit-up confusion.", "National Engineers & Steel Fabricators can plan fabrication splits and match-marking for erection where required.", "Our site-friendly fabrication support can include:"], bullets: ["Match-marking of fabricated sections", "Part identification", "Module-wise dispatch", "Bolt-hole alignment checks", "Trial fit-up where required", "Flange orientation checks", "Packing as per installation sequence", "Erection-friendly component splitting", "Site interface marking", "Dispatch documentation support"] },
      { title: "Support for Heavy Fabricated Assemblies", body: ["Heavy fabricated assemblies often need proper erection support because of weight, geometry, awkward handling or site access limitations.", "National Engineers & Steel Fabricators supports site execution for heavy fabricated assemblies such as:", "Our support focuses on helping fabricated items reach their final installed position with better control over alignment, interface fit-up and site readiness."], bullets: ["Large duct sections", "Scrubber bodies", "Heavy structural frames", "Equipment support frames", "Skid frames", "Plate-built housings", "Hoppers and bins", "Storage tanks", "Custom process equipment", "Pipe rack modules", "Large fabricated components"] },
      { title: "Punch-List Closure and Final Readiness Assistance", body: ["After installation, there may be minor pending points related to alignment, fastening, interface fit-up, access clearance, paint touch-up, support adjustment or documentation closure.", "National Engineers & Steel Fabricators can assist with punch-list closure and final readiness checks as per agreed scope.", "Punch-list support may include:"], bullets: ["Checking pending fit-up items", "Reviewing installation-related corrections", "Supporting interface mismatch resolution", "Assisting with alignment corrections", "Checking final orientation and position", "Supporting readiness for testing or commissioning", "Coordinating with client team for closure points", "Documentation support where agreed"] },
      { title: "Types of On-Site Erection Support We Provide", body: ["National Engineers & Steel Fabricators provides on-site erection support for different fabricated equipment and industrial project requirements.", "Common support types include:"], bullets: ["On-site erection support", "Industrial erection support", "Site erection support", "Equipment erection support", "Fabricated equipment installation support", "Industrial installation assistance", "Site installation support", "Positioning support", "Alignment support", "Fit-up support", "Interface checking support", "Site measurement validation", "Lifting coordination assistance", "Erection sequencing support", "Shutdown erection support", "Punch-list closure support", "Commissioning-readiness assistance", "Custom fabrication installation support"] },
      { title: "Key Features", bullets: ["On-site erection support for fabricated equipment", "Positioning, alignment and fit-up assistance", "Site measurement validation and interface checks", "Lifting coordination and erection sequencing support", "Support for heavy fabricated assemblies", "Shutdown and installation support as per agreed scope", "Match-marking and site-friendly fabrication planning", "Punch-list closure support", "Commissioning-readiness assistance where included", "Coordination with client teams and site contractors as agreed", "Support for tanks, vessels, ducts, skids, frames and custom assemblies", "Helps reduce rework caused by interface mismatch", "Helps improve site installation efficiency", "Suitable for custom manufacturing projects as per client drawing"] },
      { title: "Applications", body: ["Our on-site erection support is used across different industrial applications, including:"], bullets: ["Fabricated equipment installation", "Pressure vessel installation support", "Storage tank installation support", "Ducting installation support", "Scrubber installation support", "Hopper and bin installation support", "Skid installation support", "Heavy structural assembly erection", "Equipment support frame installation", "Pipe rack module erection", "Custom fabricated component installation", "Shutdown replacement jobs", "Plant modification projects", "Retrofit installation jobs", "Industrial project execution support", "Final fit-up and alignment assistance"] },
      { title: "Industries Served", body: ["National Engineers & Steel Fabricators provides on-site erection support for industrial clients and project teams across different sectors.", "Industries served include:"], bullets: ["Chemical plants", "Process industries", "Petrochemical units", "Oil and gas projects", "Fertilizer plants", "Utility plants", "Water treatment plants", "Effluent treatment plants", "Power projects", "Manufacturing plants", "Bulk material handling facilities", "Pollution control system projects", "Heavy engineering projects", "Industrial fabrication projects"] },
      { title: "Technical Specifications", table: { columns: ["Specification", "Details"], rows: [["Service Type", "On-Site Erection Support / Installation Assistance"], ["Equipment Category", "Custom Manufacturing (As per Client Drawing)"], ["Application", "Positioning, alignment, fit-up, interface checking and installation support"], ["Suitable For", "Fabricated equipment, ducts, skids, tanks, vessels, frames, structures and custom assemblies"], ["Build Basis", "Client drawings, installation scope, site condition and project requirement"], ["Support Scope", "Positioning, alignment, fit-up, interface validation and readiness support"], ["Site Measurement", "Available as per agreed scope"], ["Interface Checks", "Foundation, anchor, flange, duct, pipe, support and existing plant interfaces"], ["Lifting Coordination", "Support for lifting planning and erection sequencing as agreed"], ["Shutdown Support", "Available for shutdown, turnaround and retrofit installation jobs"], ["Match-Marking", "Supported where fabrication splits and site assembly are involved"], ["Trial Fit-Up", "Available before dispatch for critical assemblies where required"], ["Punch-List Support", "Available as per agreed scope"], ["Commissioning Readiness", "Assistance available where included in scope"], ["Client Coordination", "Coordination with client teams and site contractors as agreed"], ["Safety Requirements", "As per site safety requirements and client-approved procedures"], ["Documentation", "Site reports, punch-list records and support documentation as agreed"], ["Customization", "Available as per site access, crane limits, shutdown window and installation requirement"]] } },
      { title: "Site Execution and Quality Control", body: ["On-site erection support requires proper coordination between fabrication records, drawings, site conditions, lifting limitations, equipment interfaces and client safety procedures.", "Quality and execution support may include:"], bullets: ["Drawing review before site work", "Site condition review", "Foundation interface checks", "Anchor location checks", "Alignment verification", "Flange and connection interface checks", "Fit-up checks", "Module identification", "Match-marking verification", "Lifting sequence coordination", "Installation sequence support", "Punch-list review", "Final readiness checks", "Documentation support as agreed"] },
      { title: "Safety and Coordination Responsibility", body: ["Site erection work must be carried out with proper safety planning, competent supervision, approved lifting plans and client site permissions.", "National Engineers & Steel Fabricators provides on-site support as per agreed scope, while final site execution, lifting approval, safety clearance, crane operation, scaffolding, permits and contractor manpower responsibilities are finalized project-wise.", "Before starting site work, the scope should clearly define:"], bullets: ["NESF support role", "Client responsibility", "Contractor responsibility", "Manpower scope", "Tools and tackles scope", "Crane and lifting scope", "Safety permit scope", "Work-at-height requirement", "Shutdown window", "Site access condition", "Final acceptance criteria"] },
      { title: "Why Choose National Engineers?", body: ["National Engineers & Steel Fabricators is a trusted industrial fabrication and on-site erection support partner in Surat, Gujarat. We help clients connect fabrication quality with practical site installation support.", "Reasons to work with us:"], bullets: ["Experienced fabrication and erection-support team", "On-site erection support for fabricated equipment", "Positioning, alignment and fit-up assistance", "Site measurement validation and interface checking", "Lifting coordination and erection sequence support", "Support for tanks, vessels, ducts, skids and structures", "Shutdown and retrofit installation support", "Match-marking and site-friendly fabrication planning", "Punch-list closure and final readiness assistance", "Coordination with client teams and site contractors as agreed", "Fabrication knowledge helps reduce site mismatch issues", "Suitable for custom manufacturing projects as per client drawing"] },
      { title: "Details Required for Quotation", body: ["To provide the right quotation for on-site erection support, please share:"], bullets: ["Fabricated equipment details", "Installation drawings", "GA drawings", "Site location", "Site access details", "Available work area", "Foundation details", "Existing plant interface details", "Crane capacity and lifting constraints", "Handling limitations", "Shutdown window", "Required erection sequence", "Installation scope", "Manpower scope expectation", "Tools and tackles availability", "Safety requirements", "Work permit requirements", "Client contractor scope", "Expected support duration", "Punch-list support requirement", "Commissioning-readiness support requirement", "Delivery or mobilization schedule"] },
      { title: "Get On-Site Erection Support", body: ["Looking for on-site erection support in India?", "Share your fabricated equipment details, installation drawings, site access, crane limits, lifting constraints, shutdown window, erection sequence and expected support scope with National Engineers & Steel Fabricators. Our team will review your requirement and provide suitable installation assistance and site execution support as per project scope."] },
    ],
    note:
      "Share your fabricated equipment details, installation drawings, site access, crane limits, lifting constraints, shutdown window, erection sequence and expected support scope.",
    enquiry: {
      title: "Request On-site Erection Support",
      subtitle: "Share your site constraints, access, lifting limits, schedule, and installation requirements.",
      productName: "On-site Erection Support",
      buttonText: "Request Support",
    },
    faqs: [
      { question: "What is on-site erection support?", answer: "On-site erection support is installation assistance provided during positioning, alignment, fit-up, interface checking and site integration of fabricated equipment or industrial assemblies." },
      { question: "Who provides on-site erection support in Surat?", answer: "National Engineers & Steel Fabricators provides on-site erection support in Surat, Gujarat, for fabricated equipment, ducting, skids, structures, tanks, vessels and custom industrial assemblies." },
      { question: "Does NESF provide on-site erection support in India?", answer: "Yes, National Engineers & Steel Fabricators provides on-site erection support in India as per project scope, site access, crane limits, shutdown window, installation sequence and client requirements." },
      { question: "What equipment can be supported during erection?", answer: "NESF can support erection and installation assistance for fabricated equipment, pressure vessels, storage tanks, ducting systems, scrubbers, hoppers, bins, skids, support frames and heavy fabricated structures." },
      { question: "What is included in erection support?", answer: "Erection support may include positioning assistance, alignment support, fit-up support, site measurement validation, interface checks, lifting coordination, erection sequencing and punch-list closure support as agreed." },
      { question: "Does NESF provide lifting plan services?", answer: "NESF can assist with lifting coordination and erection sequencing as per agreed scope. Final lifting plans, crane operation, permits and safety approvals are handled as per client and site requirements." },
      { question: "Can NESF support shutdown installation jobs?", answer: "Yes, NESF can provide support for shutdown, turnaround, retrofit and replacement jobs where fabricated items need to be installed within a defined shutdown window." },
      { question: "What details are required to get a quotation?", answer: "To get a quotation, you can share installation drawings, equipment details, site access, crane limits, lifting constraints, shutdown window, erection sequence, safety requirements and expected support duration." },
      { question: "How does erection support reduce project risk?", answer: "Erection support helps reduce rework caused by interface mismatch, poor alignment, wrong installation sequence, access limitations and unresolved site constraints." },
      { question: "How is on-site erection support price calculated?", answer: "Price depends on site location, support duration, manpower scope, installation complexity, equipment size, lifting constraints, shutdown window, safety requirements, travel, tools scope and documentation needs." },
    ],
    seo: {
      title: "On-Site Erection Support in India | NESF",
      description:
        "On-site erection support in Surat, India, for fabricated equipment positioning, alignment, fit-up, lifting and installation assistance.",
      keywords: [
        "on-site erection support", "on-site erection support in India", "on-site erection support in Surat", "erection support services", "industrial erection support", "site erection support", "equipment erection support", "fabricated equipment installation support", "installation assistance", "industrial installation assistance", "equipment installation assistance", "site installation support", "machinery erection support", "structural erection support", "heavy fabricated equipment erection", "fabricated item installation", "fit-up support", "alignment support", "positioning support", "lifting coordination", "erection sequencing", "site measurement validation", "interface checking", "shutdown erection support", "punch-list closure support", "commissioning readiness assistance", "plant installation support", "custom fabrication installation support", "industrial fabrication company in Surat",
      ],
    },
  },
  "repair-modification-jobs": {
    title: "Industrial Repair and Modification Jobs in India",
    headline: "Repair and Modification Jobs in Surat",
    description:
      "National Engineers & Steel Fabricators provides industrial repair and modification jobs in India for fabricated equipment, heavy welded assemblies, ducting systems, structural components, supports, brackets, replacement parts, retrofit sections and plant equipment that require repair, reinforcement, modification or shutdown support.",
    pagePath: "/products/repair-modification-jobs",
    image: "/gallery/Work in progress (38).jpg",
    imageAlt: "Industrial repair and modification fabrication work by National Engineers",
    imagePosition: "center",
    quickFacts: [
      { label: "Service Type", value: "Repair / Modification Jobs" },
      { label: "Scope", value: "Repair, reinforcement, retrofit and replacement" },
      { label: "Planning", value: "Site condition and shutdown constraints" },
      { label: "Build Basis", value: "Drawings, photographs and measurements" },
    ],
    overview: [
      "Based in Sachin GIDC, Surat, Gujarat, we support repair and modification requirements as per existing equipment condition, updated drawings, site photographs, operating conditions, shutdown constraints, access limitations, material requirement, inspection scope, testing requirement and documentation needs.",
      "Our repair and modification support is suitable for industries that need to restore equipment integrity, extend equipment life, adapt existing systems to revised process requirements, reduce downtime and avoid complete replacement wherever practical.",
    ],
    sections: [
      {
        title: "Repair and Modification Jobs in Surat",
        body: ["National Engineers & Steel Fabricators is an experienced fabrication company in Surat, offering repair, reinforcement, retrofit and modification support for industrial equipment and fabricated assemblies.", "As a repair and modification support provider in India, we undertake section replacement, structural correction, nozzle addition, nozzle relocation, support upgrades, bracket fabrication, ducting repair, heavy fabricated assembly repair, alignment correction and replacement-part fabrication as per client requirement.", "Each repair or modification job is planned with attention to safety, existing equipment condition, access constraints, interface matching, fit-up accuracy, weld quality, inspection requirement and shutdown schedule."],
      },
      {
        title: "Industrial Equipment Repair and Modification",
        body: ["Industrial equipment may require repair or modification due to wear, corrosion, mechanical damage, layout change, process change, capacity change, equipment relocation, shutdown maintenance or revised project requirements.", "National Engineers & Steel Fabricators supports industrial repair and modification jobs where fabrication expertise is required to restore, strengthen or adapt existing equipment.", "Our repair and modification scope can include:"],
        bullets: ["Equipment section replacement", "Reinforcement fabrication", "Retrofit fabrication", "Structural correction", "Support upgrade", "Bracket addition", "Nozzle addition", "Nozzle relocation", "Ducting repair", "Heavy fabricated assembly repair", "Alignment correction", "Replacement-part fabrication", "Modified part fabrication", "Site-fitment support", "Inspection and documentation support"],
      },
      {
        title: "Repair, Reinforcement and Retrofit Fabrication",
        body: ["Repair, reinforcement and retrofit fabrication are required when existing equipment or structures need to be restored or upgraded instead of fully replaced.", "National Engineers & Steel Fabricators provides fabrication support for repair and retrofit requirements based on photographs, drawings, sketches, site measurements and updated process requirements.", "Our scope can include:"],
        bullets: ["Damaged section replacement", "Wear-affected section repair", "Corroded section replacement", "Reinforcement plate fabrication", "Additional stiffener fabrication", "Bracket and support addition", "Retrofitted fabricated parts", "Interface-matching replacement parts", "Modified ducting sections", "Modified structural members", "Heavy fabricated repair assemblies"],
      },
      {
        title: "Section Replacement and Replacement-Part Fabrication",
        body: ["In many repair jobs, complete equipment replacement is not required. Only damaged, worn or modified sections may need replacement.", "National Engineers & Steel Fabricators fabricates replacement sections and spare fabricated parts as per existing equipment dimensions, site measurements or revised drawings.", "Replacement-part fabrication can include:", "Replacement parts can be match-marked, packed and supplied for shutdown installation where required."],
        bullets: ["Plate sections", "Shell sections", "Duct sections", "Brackets", "Supports", "Liners", "Base plates", "Mounting plates", "Flange sections", "Structural members", "Equipment interface parts", "Custom fabricated replacement assemblies"],
      },
      { title: "Nozzle Addition, Nozzle Relocation and Interface Modification", body: ["Process changes, layout changes or equipment upgrades may require nozzle addition, nozzle relocation or interface modification.", "National Engineers & Steel Fabricators can support nozzle and interface modification as per updated drawings, P&ID requirement, site condition and inspection scope.", "Modification support may include:", "Final suitability depends on equipment design, service condition, inspection requirement and client approval."], bullets: ["New nozzle addition", "Existing nozzle relocation", "Nozzle reinforcement pad fabrication", "Flange interface changes", "Connection modification", "Branch connection support", "Duct or pipe interface changes", "Equipment opening modification", "Alignment and fit-up support", "Testing and inspection support where required"] },
      { title: "Support Upgrades, Brackets and Structural Corrections", body: ["Existing equipment and structures may require upgraded supports, additional brackets, strengthening members or alignment correction due to vibration, load change, plant modification or maintenance findings.", "National Engineers & Steel Fabricators fabricates support upgrades and structural correction components as per client drawings and site needs.", "Our scope can include:"], bullets: ["Support upgrade fabrication", "New bracket fabrication", "Additional gusset fabrication", "Stiffener addition", "Base plate modification", "Pipe support correction", "Structural member replacement", "Strengthening plate fabrication", "Alignment correction support", "Retrofit structural attachments", "Modified support frames"] },
      { title: "Ducting and Heavy Fabricated Assembly Repairs", body: ["Ducting systems, heavy fabricated assemblies, casings, hoppers, bins, scrubbers and structural frames may require repair due to wear, corrosion, impact, leakage, misalignment or modification needs.", "National Engineers & Steel Fabricators supports repair and modification of heavy fabricated assemblies using controlled fabrication and fit-up practices.", "Repair support can include:"], bullets: ["Ducting section repair", "Duct flange modification", "Casing repair", "Hopper repair", "Bin repair", "Scrubber body modification", "Heavy plate section replacement", "Structural frame repair", "Equipment support correction", "Reinforcement addition", "Interface adjustment", "Replacement duct or casing part fabrication"] },
      { title: "Shutdown Repair and Modification Support", body: ["Shutdown repair jobs must be planned carefully because available time is limited and site access may be restricted. Replacement parts should be fabricated, marked and ready before the shutdown window starts.", "National Engineers & Steel Fabricators supports shutdown repair and modification jobs with planned fabrication and site-integration support as per agreed scope.", "Shutdown support can include:"], bullets: ["Pre-shutdown drawing review", "Site photographs and measurement review", "Replacement-part fabrication", "Match-marking", "Packing as per installation sequence", "Access and lifting constraint review", "Shutdown window planning support", "Quick fit-up support", "Punch-list closure support", "Inspection and documentation support"] },
      { title: "Retrofit Fabrication for Revised Process Requirements", body: ["Plant systems may need modification when process duty, layout, capacity, equipment interface or operational requirement changes. Retrofit fabrication helps adapt existing equipment without complete replacement.", "National Engineers & Steel Fabricators provides retrofit fabrication support as per revised drawings, site condition and client requirements.", "Retrofit fabrication can include:"], bullets: ["Modified equipment sections", "New interface parts", "Additional supports", "Updated ducting sections", "Revised brackets and frames", "Access modification", "Nozzle changes", "Flange changes", "Reinforcement additions", "Replacement panels", "Modified structural assemblies"] },
      { title: "Site Measurements, Photographs and Existing Interface Matching", body: ["Repair and modification jobs often depend on existing site condition rather than only original drawings. Existing equipment may have tolerances, wear, earlier modifications or site-level differences.", "National Engineers & Steel Fabricators can review photographs, sketches, measurements and interface details to plan fabrication scope.", "Important inputs include:"], bullets: ["Current photographs", "Existing equipment drawings", "Revised modification drawings", "Site measurements", "Interface dimensions", "Nozzle and flange details", "Access limitations", "Lifting limitations", "Shutdown duration", "Operating condition", "Inspection and testing requirement"] },
      { title: "Types of Repair and Modification Jobs We Support", body: ["National Engineers & Steel Fabricators supports industrial repair and modification jobs for different fabricated equipment and plant requirements.", "Common scopes include:"], bullets: ["Industrial repair and modification jobs", "Fabrication repair services", "Fabrication modification services", "Industrial equipment repair", "Industrial equipment modification", "Retrofit fabrication services", "Shutdown repair support", "Shutdown modification support", "Section replacement fabrication", "Reinforcement fabrication", "Nozzle addition and relocation", "Support upgrade fabrication", "Bracket fabrication", "Structural correction jobs", "Ducting repair", "Heavy fabricated assembly repair", "Alignment correction", "Replacement-part fabrication", "Plant maintenance fabrication", "Custom repair fabrication as per drawing"] },
      { title: "Key Features", bullets: ["Repair and modification support as per site condition", "Suitable for fabricated equipment and industrial assemblies", "Section replacement, reinforcement and retrofit fabrication", "Nozzle addition, relocation and interface modification support", "Support upgrades, brackets and structural corrections", "Ducting and heavy fabricated assembly repair", "Shutdown-focused replacement-part fabrication", "Site photographs and drawing-based scope review", "Interface matching and fit-up accuracy focus", "Controlled fabrication and welding support", "Inspection, testing and documentation support as agreed", "Punch-list and shutdown completion support where required", "Suitable for plant maintenance, retrofit and modification projects"] },
      { title: "Applications", body: ["Our repair and modification jobs are used across different industrial applications, including:"], bullets: ["Plant shutdown jobs", "Plant maintenance jobs", "Equipment repair jobs", "Equipment modification projects", "Industrial retrofit work", "Ducting repair and modification", "Heavy fabricated assembly repair", "Structural correction jobs", "Support upgrade jobs", "Nozzle addition or relocation work", "Replacement-part fabrication", "Process layout modification", "Capacity modification projects", "Plant expansion support", "Site-fitment correction", "Custom fabrication repair work"] },
      { title: "Industries Served", body: ["National Engineers & Steel Fabricators provides repair and modification support for industrial clients across different sectors.", "Industries served include:"], bullets: ["Chemical plants", "Process industries", "Petrochemical units", "Oil and gas projects", "Fertilizer plants", "Utility plants", "Water treatment plants", "Effluent treatment plants", "Power projects", "Manufacturing plants", "Bulk material handling facilities", "Pollution control equipment projects", "Heavy engineering industries", "Industrial maintenance contractors", "EPC and project contractors"] },
      { title: "Materials of Construction", body: ["Repair and modification jobs may involve different materials depending on existing equipment MOC, service condition and revised requirement.", "Common material options include:", "Final material selection should match the existing equipment MOC, revised drawing, service media, corrosion condition, temperature, pressure and inspection requirement."], bullets: ["Mild Steel", "Carbon Steel", "Stainless Steel", "Alloy Steel", "Structural Steel", "Wear-resistant plates where required", "Liner plates where required", "Special MOC as per client specification"] },
      { title: "Technical Specifications", table: { columns: ["Specification", "Details"], rows: [["Service Type", "Repair / Modification Jobs"], ["Equipment Category", "Custom Manufacturing (As per Client Drawing)"], ["Application", "Repair, reinforcement, retrofit, replacement-part fabrication and shutdown support"], ["Suitable For", "Fabricated equipment, ducting, structures, supports, assemblies and plant equipment"], ["Build Basis", "Existing drawings, revised drawings, photographs, site measurements and duty conditions"], ["Common Scope", "Section replacement, support upgrade, nozzle modification, bracket addition and structural correction"], ["Repair Type", "Planned repair, shutdown repair, retrofit repair or custom modification"], ["Material of Construction", "MS, CS, SS, alloy steel, structural steel or as per existing equipment requirement"], ["Fabrication Scope", "Cutting, forming, fit-up, welding, reinforcement, replacement part and modification work"], ["Interface Matching", "Available as per existing equipment dimensions and site condition"], ["Shutdown Support", "Available as per agreed project scope"], ["Site Support", "Available where included in scope"], ["Welding", "As per project requirement and MOC compatibility"], ["Inspection", "Dimensional checks, fit-up checks, weld visual inspection and job-specific inspection"], ["Testing", "Leak test, pressure test or other testing where specified and applicable"], ["Documentation", "Inspection records, repair records, NDT records and QA/QC documentation as agreed"], ["Packing", "Replacement parts packed and marked for site installation"], ["Customization", "Available as per site condition, revised requirement, shutdown window and inspection scope"]] } },
      { title: "Fabrication, Inspection and Quality Control", body: ["Every repair and modification job is executed with proper attention to existing condition, revised requirement, material compatibility, fit-up quality, welding control, interface matching, inspection and documentation.", "Quality checks may include:"], bullets: ["Existing condition review", "Drawing and revised requirement review", "Photograph and site measurement review", "Material verification", "MOC compatibility check", "Replacement-part dimension check", "Fit-up inspection", "Interface matching check", "Welding quality checks", "Weld visual inspection", "Reinforcement location check", "Nozzle or support orientation check", "Dimensional inspection", "NDT where specified", "Leak or pressure testing where applicable", "Surface preparation and coating checks", "Part marking and packing checks", "Final documentation as agreed"] },
      { title: "Safety and Scope Responsibility", body: ["Repair and modification work must be planned with proper safety procedures, site permits, shutdown planning and client-approved execution methods.", "Before starting any job, the scope should clearly define:", "Final site execution, safety permits and operating clearance are handled as per client and site requirements."], bullets: ["NESF fabrication scope", "Client responsibility", "Site contractor responsibility", "Manpower scope", "Tools and tackles scope", "Crane and lifting scope", "Hot-work permit requirement", "Confined-space requirement", "Work-at-height requirement", "Shutdown window", "Inspection hold points", "Testing requirement", "Final acceptance criteria"] },
      { title: "Why Choose National Engineers?", body: ["National Engineers & Steel Fabricators is a trusted fabrication repair and modification support company in Surat, Gujarat. We help industrial clients repair, modify, reinforce and retrofit fabricated equipment as per drawings, site conditions and shutdown requirements.", "Reasons to work with us:"], bullets: ["Experienced repair and modification support provider in India", "Reliable fabrication company in Surat, Gujarat", "Repair, reinforcement and retrofit fabrication support", "Section replacement and replacement-part fabrication", "Nozzle addition, nozzle relocation and support upgrades", "Ducting and heavy fabricated assembly repair", "Shutdown-focused fabrication and packing support", "Site measurement and interface matching focus", "Controlled fit-up, welding and inspection support", "QA/QC documentation and NDT support where specified", "Suitable for chemical, process, utility, power, oil and gas and heavy industry"] },
      { title: "Details Required for Quotation", body: ["To provide the right quotation for repair and modification jobs, please share:"], bullets: ["Existing equipment photographs", "Existing equipment drawings", "Revised modification drawings", "Site measurements", "Damage details or modification requirement", "Operating conditions", "Service history", "Material of construction", "Current problem or repair scope", "Required section replacement details", "Nozzle or support modification details", "Access constraints", "Lifting constraints", "Shutdown window", "Site work constraints", "Inspection requirement", "NDT requirement", "Testing requirement", "Documentation requirement", "Expected completion timeline", "Site location"] },
      { title: "Request Assessment for Repair / Modification Job", body: ["Looking for industrial repair and modification support in India?", "Share your equipment photographs, drawings, revised requirements, operating conditions, site constraints, shutdown window, inspection requirements and expected completion timeline with National Engineers & Steel Fabricators. Our team will review your requirement and suggest a suitable repair, reinforcement, retrofit or modification route based on the agreed project scope."] },
    ],
    note:
      "Share your equipment photographs, drawings, revised requirements, operating conditions, site constraints, shutdown window, inspection requirements and expected completion timeline.",
    enquiry: {
      title: "Request Support for a Repair / Modification Job",
      subtitle: "Share photos, drawings, operating conditions, site constraints, and inspection requirements.",
      productName: "Repair / Modification Job",
      buttonText: "Request Assessment",
    },
    faqs: [
      { question: "What are industrial repair and modification jobs?", answer: "Industrial repair and modification jobs include repair, reinforcement, retrofit, section replacement, support upgrades, nozzle changes, structural corrections and replacement-part fabrication for existing plant equipment or fabricated assemblies." },
      { question: "Who provides repair and modification jobs in Surat?", answer: "National Engineers & Steel Fabricators provides repair and modification jobs in Surat, Gujarat, for fabricated equipment, ducting, structural components, supports, brackets, replacement parts and heavy fabricated assemblies." },
      { question: "Does NESF provide repair and modification support in India?", answer: "Yes, National Engineers & Steel Fabricators provides repair and modification support in India as per drawings, site photographs, operating conditions, shutdown constraints, inspection requirements and project scope." },
      { question: "What types of repair jobs can NESF support?", answer: "NESF can support section replacement, reinforcement, ducting repair, structural repair, bracket fabrication, support upgrade, alignment correction, replacement-part fabrication and retrofit fabrication jobs." },
      { question: "Can nozzle addition or relocation be done?", answer: "Yes, nozzle addition or relocation can be supported where feasible as per revised drawings, equipment condition, service requirements, material compatibility, inspection scope and client approval." },
      { question: "Can repair work be done during plant shutdown?", answer: "Yes, repair and modification jobs can be planned for shutdown windows with replacement-part fabrication, match-marking, packing, access planning and inspection support as per agreed scope." },
      { question: "What information is required before a repair job?", answer: "Important inputs include current photographs, existing drawings, revised requirements, operating conditions, service history, access limitations, shutdown window, inspection requirements and testing needs." },
      { question: "What is retrofit fabrication?", answer: "Retrofit fabrication means modifying or adding fabricated parts to existing equipment or systems to match revised process, layout, capacity, access or operational requirements." },
      { question: "What quality checks are done during repair and modification work?", answer: "Quality checks may include existing condition review, material verification, fit-up inspection, interface matching, weld visual inspection, dimensional inspection, NDT where specified and testing where applicable." },
      { question: "How is repair and modification job price calculated?", answer: "Price depends on repair scope, equipment condition, material, replacement-part quantity, fabrication complexity, site access, shutdown window, welding, NDT, testing, manpower scope, documentation and timeline." },
    ],
    seo: {
      title: "Industrial Repair & Modification Jobs in India | NESF",
      description:
        "Industrial repair and modification jobs in Surat, India, for fabricated equipment, retrofit, reinforcement and shutdown support.",
      keywords: [
        "industrial repair and modification jobs", "repair and modification jobs", "repair and modification jobs in India", "repair and modification jobs in Surat", "industrial equipment repair", "industrial equipment modification", "fabrication repair services", "fabrication modification services", "retrofit fabrication services", "industrial retrofit jobs", "plant modification jobs", "shutdown repair support", "shutdown modification support", "equipment repair and retrofit", "heavy fabricated assembly repair", "ducting repair", "structural repair fabrication", "section replacement fabrication", "reinforcement fabrication", "nozzle addition", "nozzle relocation", "support upgrade", "bracket fabrication", "alignment correction", "replacement part fabrication", "site modification support", "plant maintenance fabrication", "industrial maintenance support", "custom repair fabrication", "custom modification fabrication", "inspection and documentation", "QA/QC repair documentation",
      ],
    },
  },
} satisfies Record<string, ProductDetail>;

export function buildProductMetadata(product: ProductDetail): Metadata {
  return buildMetadata({
    title: product.seo.title,
    description: product.seo.description,
    path: product.pagePath,
    image: product.image,
    keywords: product.seo.keywords,
    robots: { index: true, follow: true },
  });
}
